version: 2
updates:
# --- C# / .NET (NuGet) ---
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "12:00"
  target-branch: "dev"

# --- Go modules ---
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "12:00"
  target-branch: "dev"

# --- GitHub Actions ---
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "12:00"
  target-branch: "dev"
# --- Dart packages (pub) ---
- package-ecosystem: "pub"
  directory: "/dupes"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "12:00"
  target-branch: "dev"
