<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.10" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.0.5" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.52.0" />
    <PackageReference Update="FSharp.Core" Version="9.0.303" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FolderManager\FolderManager\FolderManager.csproj" />
  </ItemGroup>

</Project>
