package cmd

/*
Copyright © 2026 Robert Impey robert-impey@users.noreply.github.com
*/

import (
	"fmt"

	"github.com/robert-impey/tools/gensyn/internal"
	"github.com/spf13/cobra"
)

var (
	locationsFile string
	foldersFile   string
	autoGenFolder string
)

var robocopyCmd = &cobra.Command{
	Use:   "robocopy",
	Short: "Generates robocopy scripts for managed folders",
	Long: `Generates robocopy scripts for managed folders.

This command reads a locations file and a folders file, then produces
autogenerated robocopy scripts into the specified output directory.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if locationsFile == "" {
			return fmt.Errorf("locations file is required (use -l or --locations)")
		}
		if foldersFile == "" {
			return fmt.Errorf("folders file is required (use -f or --folders)")
		}
		if autoGenFolder == "" {
			return fmt.Errorf("auto-generated folder is required (use -a or --autogen)")
		}

		fmt.Printf("Reading locations from: %s\n", locationsFile)
		fmt.Printf("Reading folders from: %s\n", foldersFile)
		fmt.Printf("Using auto-generated folder: %s\n", autoGenFolder)

		folderManager, err := internal.CreateFolderManager(locationsFile, foldersFile)
		if err != nil {
			return err
		}

		return folderManager.GenerateRobocopyScripts(autoGenFolder)
	},
}

func init() {
	rootCmd.AddCommand(robocopyCmd)

	robocopyCmd.Flags().StringVarP(&locationsFile, "locations", "l", "", "The locations file")
	robocopyCmd.Flags().StringVarP(&foldersFile, "folders", "f", "", "The folders file")
	robocopyCmd.Flags().StringVarP(&autoGenFolder, "autogen", "a", "", "The folder for the autogen'd scripts")

	// If any of these should be required:
	err := robocopyCmd.MarkFlagRequired("locations")
	if err != nil {
		return
	}
	err = robocopyCmd.MarkFlagRequired("folders")
	if err != nil {
		return
	}
	err = robocopyCmd.MarkFlagRequired("autogen")
	if err != nil {
		return
	}
}
