name: CMake

on:
  push:
    branches:
      - "dev"
      - "prod"

jobs:
  build_managed_folders:
    name: Managed Folders
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: ./ManagedFolders
          build-dir: ./ManagedFolders/out
