name: .NET CI

on:
  push:
    branches:
      - "dev"
      - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - TidyFolder
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Debug)
        run: dotnet build --no-restore --configuration Debug

      - name: Test (Debug)
        run: dotnet test --no-build --verbosity normal --configuration Debug