name: Go CI

on:
  push:
    branches:
      - "dev"
      - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - cron-setter
          - gensyn
          - lmf
          - logs-deleter
          - permreset
          - staydeleted
          - tdyfldr
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Cache Go modules
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            $GOPATH/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...