# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"
      - "dev"

jobs:
  build_cron_setter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cron-setter
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build_generate_synch_scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generate-synch-scripts
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build_logs_deleter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logs-deleter
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build_run_stay_deleted:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./run-stay-deleted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build_stay_deleted:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./staydeleted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
