name: Rust

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"
      - "dev"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_tidy_folder:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tidy-folder
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
